# Generated by Django 3.0.5 on 2020-04-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocard',
            name='photo',
            field=models.ImageField(default='lifestyleuploads/nikhilcompressed1.jpg', upload_to='lifestyleuploads'),
        ),
    ]
