# Generated by Django 3.0.5 on 2020-04-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='sdfsdfsdfsdfsdf', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='githublink',
            field=models.URLField(default='https://abcddf.com', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projectimages/defaultproject.jpg', upload_to='projectimages'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='default_project_name', max_length=70),
        ),
        migrations.AddField(
            model_name='project',
            name='technologystack',
            field=models.CharField(default='https://avd.com', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='videolink',
            field=models.URLField(default='https://dfsd.com', max_length=1000),
            preserve_default=False,
        ),
    ]
