# Generated by Django 3.0.5 on 2020-04-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200410_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='githublink',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologystack',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='videolink',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
