# Generated by Django 3.0.5 on 2020-04-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200410_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='dfdf', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='githublink',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologystack',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='videolink',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
