# Generated by Django 3.0.5 on 2020-04-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200414_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='projectimages/defaultproject.jpg', upload_to='projectimages'),
        ),
    ]
