# Generated by Django 3.0.5 on 2020-06-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200414_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectlink',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
